server:
  port: 8761

eureka:
  client:
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://127.0.0.1:${server.port}/eureka
      ###自己是注册中心，是否要将自己注册到注册中心去,但是集群的时候需要设置为true
    register-with-eureka: false
    ###自己是注册中心，不需要去检索服务信息
    fetch-registry: false

spring:
  application:
    name: eurka-server
